### ISSUE TITLE
Feature request: allow for an array of schemaJsonOutputPath (and other files)

### ISSUE THREAD

**Issue by good-idea** [ricokahler/sanity-codegen#172]
it would be nice to be able to output the schema definitions and `.json` file to multiple locations.

Updating the `SanitySchemaCodegen.schemaTypesOutputPath` to:

```
    /**
     * Optionally provide a destination path (or multiple paths) to the resulting sanity schema types.
     * The default value is `schema-types.d.ts`
     */
    schemaTypesOutputPath?: string | string[];
```

This would be a non-breaking change. I'd be happy to make a PR!

**Comment by ricokahler** [comment]
Can you provide some more details on your use case? I like the idea but it might have some negative consequences. The new alpha uses namespaces and ambient types which is nice because you don't have to import anything to start using the types but it might cause issues when there are two definitions with the same identifier in the same namespace. If those definitions are exactly the same, it might not be an issue though.
