### ISSUE TITLE
SanitySlug type removed?

### ISSUE THREAD

**Issue by PaulPCIO** [ricokahler/sanity-codegen#65]
I was wondering why hardcode the slug typings instead of adding it as an importable type?

eg looking at a previous code the slug was [typed seperatly](https://github.com/ricokahler/sanity-codegen/blob/13250d60892bfc95b73d88b28e88b574a31935a7/src/generate-types.ts#L335).

Now the slug shape is injected into each [parent type](https://github.com/ricokahler/sanity-codegen/blob/f1c036b5a2d64f58877ef069c745f0efd7ff5490/src/generate-types.ts#L273-L275).

here are some use cases where the SanitySlug was very helpfull:
```ts
// fetching data without using the codegen client could still be typed correctly

type ResponseData = Array<{ slug:SanitySlug  }>
const data = sanityClient.fetch<ResponseData>(*[_type=="users"]{ slug })

// it was also usefull when creating documents, eg having a helper function to ensure correct format

export function createSlug(current: string): SanitySlug {
  return { _type: 'slug', current }
}

sanityClient.create({
 _type:"users",
  rfq: createSlug("my-slug"),
 ...
})
```

**Comment by ricokahler** [comment]
Hi @PaulPCIO ,

The reason that type was removed was related to #27.

Someone else correctly reported that their slug entities did not have the right `_type`. When first building this lib, my assumption was that any slug entity would have their `_type` value be literally `'slug'` always so it made sense to create a specific type.

However, what I learned is that the`slug` type behaves like the `object`, `image`, and `file` types where you can extend them and create any named type in sanity. E.g.

```js

// 1. first define two "named" types
const foo = {
  name: "foo",
  type: "object",
  fields: [{ name: "title", type: "string" }]
};

const imageWithDescription = {
  name: "imageWithDescription",
  type: "image",
  fields: [{ name: "description", type: "string" }]
};

const namedSlug = {
  name: 'mySlug',
  type: 'slug',
}

// 2. use the named types in another type
const myDocument = {
  name: "myDocument",
  title: "My Document",
  type: "document",
  fields: [
    { name: "image", type: "imageWithDescription" },
    { name: "aFoo", type: "foo" },
    { name: "bar", type: "mySlug" },
  ]
};
```

The resulting types are like so:

```ts
export type Foo = {
  _type: "foo";
  title?: string;
};

export type ImageWithDescription = {
  _type: "imageWithDescription";
  asset: SanityAsset;
  crop?: SanityImageCrop;
  hotspot?: SanityImageHotspot;
  description?: string;
};

export type MySlug = { _type: "mySlug"; current: string };

export interface MyDocument extends SanityDocument {
  _type: "myDocument";
  image?: ImageWithDescription;
  aFoo?: Foo;
  bar?: MySlug;
}

export type Documents = MyDocument;
```

The nuance here is that the type of `MyDocument['bar']['_type']` is actually `'mySlug'` not just `'slug'`.

I think for consistency, I'd rather leave slug behaving like image and file but I agree it's weird (because you can't append fields to slugs).

Does that make sense? If you have alternate suggestions I'm open to hearing 'em!

My apologies for the breaking change!

**Comment by PaulPCIO** [comment]
Hey, thanks I understand now. I will create a generic type from my side for the use case that I posted as it is more of a controlled situation.
