### ISSUE TITLE
Automatic reference expansion

### ISSUE THREAD

**Issue by wadamek65** [ricokahler/sanity-codegen#84]
Currently having a document which has a lot of references or references that are nested requires expanding everything manually and applying typescript hacks which makes the code type-safe. I think it would be nice if all query methods had an `autoExpand?: boolean` argument that could automatically call expand and produce appropriate types.

Do you think this is something that could be implemented? If so I would be willing to work on this.

**Comment by ricokahler** [comment]
I'm actually looking to radically simplify the client so that it just magically works with groq (so this entails writing groq codegen). This will be a big undertaking but I think it's the right move and will handle use cases like yours in the way that most natural to sanity.

Because of this, I'm currently hesitant to add more features to the current client in fear of it becoming too unstable. 😅

Until that's done, for now, I would recommend querying with groq via the first party clients (either `@sanity/client` or `picosanity`) and then composing the resulting type derived from the generated ones.

```ts
import Sanity from '@sanity/client';
import * as Schema from '../codegen-output';

const query = `
  * [ _type == 'blog' ] {
    ...,
    author -> { ... }
  }
`;

type Result = Array<Omit<Schema.Blog, 'author'> & { author: Schema.Author }>

const result = await sanity.fetch<Result>(query);
```

---

However, if you want to get fancy, you could probably do this with the current client and some recursive functions.

```ts
// 🔴  i have not ANY tested this whatsoever lol
import * as Schema from '../codegen-output';
import { createClient } from 'sanity-codegen';

const sanity = createClient</* ... */>({/* ... */});

type RecursiveExpand<T> = {
  [P in keyof T]: T[P] extends Schema.SanityReference<infer U>
    ? RecursiveExpand<U>
    : RecursiveExpand<T[P]>
};

const maybeExpand = async (t: any) => t?._type === 'reference' ? await sanity.expand(t) : t;

async function fullyExpand<T>(obj: T): Promise<RecursiveExpand<T>> {
  if (typeof obj !== 'object' || !obj) return obj;

  if (Array.isArray(obj)) return await Promise.all(obj.map(maybeExpand));

  const entries = await Promise.all(
    Object
      .entries(obj)
      .map(async ([k, v]) => [k, await maybeExpand(v)] as const)
  );

  return Object.fromEntries(entries);
}
```

**Comment by wadamek65** [comment]
@ricokahler Thanks for the response. Yeah the second example is something similar that I am already doing, but I figured since I was working around it I might as well contribute and submit a PR to the package. 

Your reasoning makes sense to me - since there are plans for parsing groq then might as well not waste time/resources on adding features that will be scrapped later. How is the work progressing? Is there something that can be helped with?

**Comment by ricokahler** [comment]
Work on the feature is only preliminary. At this time there's not much but I'll keep you in mind. Thanks for the suggestion! For now I'll close this issue.
